[2021-04-23 09:33:50,809] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 09:33:59,296] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_detail
[2021-04-23 09:49:09,234] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 09:49:18,277] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 09:49:26,046] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_detail
[2021-04-23 09:55:33,639] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 09:55:42,724] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 09:55:50,660] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_detail
[2021-04-23 10:02:29,566] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 10:03:13,628] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 10:03:51,460] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 10:03:59,779] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 10:05:14,643] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 10:05:19,334] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move
[2021-04-23 10:10:41,157] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 10:10:44,662] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 10:10:48,202] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_002
[2021-04-23 11:03:40,054] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 11:03:43,637] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 11:03:47,187] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_002
[2021-04-23 11:06:42,179] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 11:06:45,630] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 11:06:49,091] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_002
[2021-04-23 11:08:59,221] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 11:09:02,919] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_001
[2021-04-23 11:09:06,517] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_stolocation_move_abnormal_002
