[2021-03-23 09:10:23,992] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-23 09:10:26,760] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration
[2021-03-23 09:13:45,577] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_001
[2021-03-23 09:13:51,065] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_001
[2021-03-23 09:13:55,499] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_001
[2021-03-23 09:13:59,934] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_002
[2021-03-23 09:14:04,294] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_003
[2021-03-23 09:14:08,729] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_004
[2021-03-23 09:14:13,263] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_004
[2021-03-23 09:14:17,855] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_005
[2021-03-23 09:14:22,228] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_006
[2021-03-23 09:29:51,830] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:29:54,382] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:29:55,687] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:29:57,316] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2021-03-23 09:29:58,753] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2021-03-23 09:30:00,108] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2021-03-23 09:30:01,658] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2021-03-23 09:30:07,312] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2021-03-23 09:30:10,426] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2021-03-23 09:30:13,402] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2021-03-23 09:30:16,319] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add
[2021-03-23 09:30:19,866] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add
[2021-03-23 09:30:23,619] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add
[2021-03-23 09:30:27,383] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:30:30,975] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:30:34,634] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:30:38,218] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:30:41,737] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:30:45,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:30:48,831] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:30:52,397] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:30:55,766] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:30:59,385] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_add
[2021-03-23 09:31:07,025] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_edit
[2021-03-23 09:31:11,388] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_edit
[2021-03-23 09:31:16,021] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_edit
[2021-03-23 09:31:20,687] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:31:25,554] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:31:30,304] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:31:35,096] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:44:43,183] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:44:45,683] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:44:47,247] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:47:12,802] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:47:15,698] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:47:17,130] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_name_abnormal
[2021-03-23 09:47:18,571] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2021-03-23 09:47:20,069] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2021-03-23 09:47:21,623] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom_code_abnormal
[2021-03-23 09:47:23,242] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_orgcom
[2021-03-23 09:47:29,494] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2021-03-23 09:47:32,525] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2021-03-23 09:47:35,455] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_orgcom_name_abnormal
[2021-03-23 09:47:38,464] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add
[2021-03-23 09:47:41,965] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add
[2021-03-23 09:47:45,603] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_add
[2021-03-23 09:47:49,155] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:47:52,713] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:47:56,376] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:48:00,053] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:48:03,483] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_code_add
[2021-03-23 09:48:07,047] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:48:10,546] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:48:14,013] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:48:17,572] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_add
[2021-03-23 09:48:21,111] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_user_add
[2021-03-23 09:48:28,779] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_edit
[2021-03-23 09:48:33,218] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_edit
[2021-03-23 09:48:37,933] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_username_edit
[2021-03-23 09:48:42,704] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:48:47,368] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:48:51,957] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 09:48:56,653] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_org_tel_edit
[2021-03-23 10:03:07,277] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_001
[2021-03-23 10:06:20,328] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_001
[2021-03-23 10:07:31,748] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_001
[2021-03-23 10:07:37,297] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_002
[2021-03-23 10:07:41,612] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_003
[2021-03-23 10:15:43,111] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_001
[2021-03-23 10:15:48,542] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_002
[2021-03-23 10:15:52,862] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_003
[2021-03-23 10:15:57,235] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_004
[2021-03-23 10:44:00,592] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_001
[2021-03-23 10:44:05,929] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_002
[2021-03-23 10:44:10,482] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_003
[2021-03-23 10:44:14,945] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_004
[2021-03-23 10:44:19,399] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_005
[2021-03-23 10:44:23,937] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_006
[2021-03-23 10:44:28,454] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_007
[2021-03-23 10:44:33,117] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_008
[2021-03-23 10:48:37,412] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_001
[2021-03-23 10:48:41,816] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_002
[2021-03-23 10:48:45,189] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_003
[2021-03-23 10:48:48,674] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_004
[2021-03-23 10:48:52,163] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_005
[2021-03-23 10:48:55,764] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_006
[2021-03-23 10:48:59,317] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_007
[2021-03-23 10:49:03,001] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Compound_abnormal_008
[2021-03-23 14:08:00,877] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_wo
[2021-03-23 14:10:09,519] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_wo
[2021-03-23 14:13:58,956] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_wo
[2021-03-23 14:16:54,418] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_wo
